#
server:
  port: 9000
#
# log
logging:
  file: ${spring.application.name}
  path: ${user.home}/logs

#
#spring
spring:
  application:
    name: eureka-server
  profiles:
    active: local
  cloud:
    inetutils:
      # 多网卡环境下的IP选择
      ignored-interfaces:
        - docker0
        - veth.*
#
# eureka
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    serviceUrl:
      # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
      # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
      # 指明了应用的URL
      defaultZone: http://localhost:${server.port}/eureka/
